---
title: Stel de sprite coördinaten in Scratch in
hero_image: images/banner.png
description: Hoe de sprite coördinaten in Scratch in te stellen
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Stel coördinaten in
