---
title: Scratch मध्ये स्प्राइटचे समन्वय सेट करा
hero_image: images/banner.png
description: Scratch मध्ये स्प्राइटचे समन्वय कसे सेट करावे
original_url:
theme: cc-prototype
duration: 0
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: समन्वय सेट करा
