---
title: Scratchのスプライトの座標 (ざひょう) を設定する
hero_image: images/banner.png
description: Scratchのスプライトの座標 (ざひょう) を設定する方法について学ぶ
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: 座標を設定
