---
title: Definir as coordenadas de um actor no Scratch
hero_image: images/banner.png
description: Como definir as coordenadas de um actor no Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Definir coordenadas
