---
title: Lege die Koordinaten einer Figur in Scratch fest
hero_image: images/banner.png
description: So legst du die Koordinaten einer Figur in Scratch fest
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Koordinaten festlegen
