---
title: Določi koordinate figure v Scratchu
hero_image: images/banner.png
description: Kako določiti koordinate figure v Scratchu
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Določi koordinate
