---
title: Scratch වල sprite ගේ ඛණ්ඩාංකය සකසන්න
hero_image: images / banner.png
description: Scratch වල sprite ගේ ඛණ්ඩාංක සකසන්නේ කෙසේද
original_url:
theme: cc-ප්‍රදර්ශකය
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: ඛණ්ඩාංක සකසන්න
